duplicated replacement
Financial-Times/delivery-varnish pull request #126
Opened 2024-03-26 12:25 UTC by antoanFT

# Description

## What

Please be specific and try to describe your thought process. State the obvious, since this might be the first time the reviewer is looking at the code

## Why

Copy (if there is one) the text of the original Trello/JIRA ticket in here, with a link back to it for the curious.

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

## DoD - Ensure all relevant tasks are completed before marking this PR as "Ready for review"

- [ ] Test coverage is not significantly decreased
- [ ] All PR checks have passed
- [ ] Changes are deployed on dev before asking for review
- [ ] Documentations remains up-to-date
  - [ ] OpenAPI definition file is updated
  - [ ] README file is updated
  - [ ] Documentation is updated in upp-docs and upp-public-docs
  - [ ] Architecture diagrams are updated

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2024-03-26 12:34 UTC, dbelev approved these changes

2024-03-27 07:11 UTC, epavlova requested changes
Thanks so much for finding the issue!
Let's fix that on API Gateway side so we don't have to hardcode those wrong paths on our side.

2024-03-27 10:55 UTC, dbelev submitted a review, later dismissed

2024-03-27 12:20 UTC, dbelev approved these changes

2024-03-28 07:25 UTC, epavlova approved these changes
**fix (not-blocking):** If you have gone through the pattern above with the regex, the next endpoint to the same service would have come with no varnish changes.

2024-03-28 07:26 UTC, merged