Adding the live event validator routes.
Financial-Times/delivery-varnish pull request #98
Opened 2021-12-01 07:59 UTC by martin-stanchev

# Description

## What

Enabling validating of Live Events

## Why
[JIRA ticket](https://financialtimes.atlassian.net/browse/UPPSF-2824)

## Anything, in particular, you'd like to highlight to reviewers

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [ ] Documentation
- [ ] Breaking change
- [x] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2021-12-01 10:55 UTC, atanasdinov requested changes

2021-12-01 10:55 UTC, atanasdinov commented on default.vcl
> +backend upp_internal_live_event_validator {
Let's remove this backend since we won't be deploying `internal` version of the service for now.

2021-12-03 16:37 UTC, atanasdinov approved these changes

2021-12-06 15:49 UTC, dtvalk-ov submitted a review, later dismissed

2022-02-14 13:37 UTC, atanasdinov approved these changes

2022-02-14 13:42 UTC, dtvalk-ov approved these changes

2022-02-28 09:11 UTC, merged